name: wp-plugins
on:
  pull_request:
    paths:
      - 'packages/wp-plugins/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier PHP
      run: npm run prettier-php -w packages/wp-plugins

    - name: Run ESLint
      run: npm run eslint -w packages/wp-plugins

    - name: Run Stylelint
      run: npm run stylelint -w packages/wp-plugins
